export const documentIds: Record<string, string> = {
  'README.md': '',
  'CONTRIBUTING.md': 'contributing',
  'docs/README.md': 'guides',
  'docs/getting-started.md': 'getting-started',
  'docs/gateway-api-primer.md': 'concepts/gateway-api',
  'docs/authorization-and-ownership.md': 'concepts/authorization-and-ownership',
  'docs/access-required.md': 'guides/access-required',
  'docs/cloudflare-tunnel.md': 'reference/cloudflare-tunnel',
  'docs/cloudflare-dns.md': 'reference/cloudflare-dns',
  'docs/cloudflare-access-policy.md': 'reference/cloudflare-access-policy',
  'docs/cloudflare-access-application.md': 'reference/cloudflare-access-application',
  'docs/annotations.md': 'reference/annotations',
  'docs/compatibility.md': 'operations/compatibility',
  'docs/connector-hardening.md': 'operations/connector-hardening',
  'docs/service-mesh.md': 'guides/service-mesh',
  'docs/troubleshooting.md': 'operations/troubleshooting',
  'docs/TESTING.md': 'contributing/testing',
  'docs/CLOUDFLARE_CLIENT.md': 'contributing/cloudflare-client',
  'examples/basic/README.md': 'examples/basic',
  'examples/multi-service/README.md': 'examples/multi-service',
  'examples/external-target/README.md': 'examples/external-target',
  'examples/with-rancher/README.md': 'examples/with-rancher',
}
export const groups = [
  ['Start here', ['', 'getting-started', 'guides']],
  ['Concepts', ['concepts/']],
  ['Guides', ['guides/']],
  ['Resource reference', ['reference/']],
  ['Generated schemas', ['schemas/']],
  ['Helm chart', ['helm/']],
  ['Operations', ['operations/']],
  ['Examples', ['examples/']],
  ['Contributing', ['contributing', 'contributing/']],
] as const
